// 같은 사업자(SBS아카데미AIX학원) 공식 포트폴리오(sbsart.com, 전체 16,198건 중 2026-09-21 기준 선정)의
// 실제 게시물 데이터. 이미지·영상은 원본 CDN/유튜브를 그대로 참조(재호스팅 안 함), 소개·사용툴·제작기간은
// 원본 상세페이지(view.asp)의 공개 정보를 그대로 옮김. sbsart.com은 계속 갱신되므로 주기적 재확인 필요.
export type CourseKey = "graphic" | "motion" | "cg" | "interior";

export type PortfolioItem = {
  id: string; // sbsart.com seq
  course: CourseKey;
  title: string;
  student: string;
  branch: string;
  date: string;
  category: string; // sbsart.com 카테고리 표기
  intro: string; // 작품 소개
  tools: string; // 사용 툴
  duration?: string; // 제작 의도(기간)
  program?: string; // 수강 과정
  img: string;
  video?: string; // 유튜브 embed URL
  sourceHref: string; // 원본 sbsart.com 링크(출처 표기용)
};

export const portfolioItems: PortfolioItem[] = [
  {
    id: "21186",
    course: "graphic",
    title: "함승보 학생 작품",
    student: "함승보",
    branch: "대전지점",
    date: "2026-09-04",
    category: "시각편집",
    intro: "OHTANI",
    tools: "Photoshop, Illustrator",
    duration: "15일",
    program: "편집 포폴",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/02f49ccc0fed00020fed0fedcba98765.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21186&selMater=dtp",
  },
  {
    id: "21181",
    course: "graphic",
    title: "홍수정 학생 작품",
    student: "홍수정",
    branch: "청주지점",
    date: "2026-09-01",
    category: "시각편집",
    intro: "Sunny Bite Dessert Cafe 마케팅 콘텐츠 디자인",
    tools: "Photoshop, Illustrator, ChatGPT, Midjourney",
    duration: "2주",
    program: "AI마케팅디자인",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/03ee52d4876500028765876543210fed.png",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21181&selMater=dtp",
  },
  {
    id: "21134",
    course: "graphic",
    title: "윤현지 수강생 작품",
    student: "윤현지",
    branch: "분당지점",
    date: "2026-07-23",
    category: "시각편집",
    intro: "Mellow Table Brand",
    tools: "Photoshop, Illustrator, Midjourney, ChatGPT, Gemini",
    duration: "2달",
    program: "브랜딩 디자인",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/03cacacc0fed00020fed0fedcba98765.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21134&selMater=dtp",
  },
  {
    id: "21125",
    course: "graphic",
    title: "조혜민 학생 작품",
    student: "조혜민",
    branch: "울산지점",
    date: "2026-07-21",
    category: "시각편집",
    intro: "'베이글베어' 브랜딩 디자인",
    tools: "Photoshop, Illustrator",
    duration: "5일",
    program: "편집포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/02b51c94876500028765876543210fed.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21125&selMater=dtp",
  },
  {
    id: "21117",
    course: "graphic",
    title: "문해은 학생 작품",
    student: "문해은",
    branch: "광주지점",
    date: "2026-07-10",
    category: "시각편집",
    intro: "패키지와 메모지 아트",
    tools: "Photoshop, Illustrator",
    duration: "7일",
    program: "시각편집 포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/04595c00cba90002cba9cba987654321.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21117&selMater=dtp",
  },
  {
    id: "21063",
    course: "graphic",
    title: "빙그레 링키바 - 패키지 리디자인",
    student: "임아린",
    branch: "광주지점",
    date: "2026-05-18",
    category: "시각편집",
    intro: "빙그레 링키바 패키지 리디자인",
    tools: "Photoshop, Illustrator",
    duration: "2주",
    program: "편집디자인 포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/033164dc0fed00020fed0fedcba98765.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21063&selMater=dtp",
  },
  {
    id: "21197",
    course: "motion",
    title: "정예은 학생 작품",
    student: "정예은",
    branch: "홍대지점",
    date: "2026-09-18",
    category: "영상/모션",
    intro: "(광고) 다이슨",
    tools: "프리미어, 에프터이펙트, Cinema4D, Octane, Substance Painter, GPT",
    program: "모션학과(3D)",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/0320cc0c0fed00020fed0fedcba98765.png",
    video: "https://www.youtube.com/embed/Cc3PXu9Qgow",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21197&selMater=%EB%AA%A8%EC%85%98%EA%B7%B8%EB%9E%98%ED%94%BD",
  },
  {
    id: "21193",
    course: "motion",
    title: "김영현 학생작품",
    student: "김영현",
    branch: "대구지점",
    date: "2026-09-08",
    category: "영상/모션",
    intro: "팻로스",
    tools: "애프터이펙트, 영상AI",
    duration: "3주",
    program: "모션그래픽",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/03ada610cba90002cba9cba987654321.png",
    video: "https://www.youtube.com/embed/NNibcskwhGA",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21193&selMater=%EB%AA%A8%EC%85%98%EA%B7%B8%EB%9E%98%ED%94%BD",
  },
  {
    id: "21184",
    course: "motion",
    title: "김정민 학생 작품",
    student: "김정민",
    branch: "인천지점",
    date: "2026-09-03",
    category: "영상/모션",
    intro: "카카오택시 2D 모션그래픽",
    tools: "애프터이펙트, 일러스트레이터",
    duration: "60일",
    program: "모션그래픽 과정",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/01fdd634876500028765876543210fed.jpg",
    video: "https://www.youtube.com/embed/4kzbAEaK8UI",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21184&selMater=%EB%AA%A8%EC%85%98%EA%B7%B8%EB%9E%98%ED%94%BD",
  },
  {
    id: "21178",
    course: "motion",
    title: "지윤서 학생 작품",
    student: "지윤서",
    branch: "대전지점",
    date: "2026-08-26",
    category: "영상/모션",
    intro: "유에포의 모험기 - 이상을 향해서",
    tools: "Photoshop, Illustrator, After Effects",
    duration: "표현 1주, 구현 7주",
    program: "모션포폴",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/0369b39c0fed00020fed0fedcba98765.jpg",
    video: "https://www.youtube.com/embed/s_Cj76Pc1i8",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21178&selMater=%EB%AA%A8%EC%85%98%EA%B7%B8%EB%9E%98%ED%94%BD",
  },
  {
    id: "21127",
    course: "motion",
    title: "김민지 학생 작품",
    student: "김민지",
    branch: "울산지점",
    date: "2026-07-22",
    category: "영상/모션",
    intro: "디바마을 퀸가비 인트로",
    tools: "Illustrator, Photoshop, After Effects, Cinema4D",
    duration: "15일",
    program: "모션포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/01e9195c0fed00020fed0fedcba98765.jpg",
    video: "https://www.youtube.com/embed/px1oDGdyebg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21127&selMater=%EB%AA%A8%EC%85%98%EA%B7%B8%EB%9E%98%ED%94%BD",
  },
  {
    id: "21012",
    course: "motion",
    title: "강민석 학생 작품",
    student: "강민석",
    branch: "광주지점",
    date: "2026-05-08",
    category: "영상/모션",
    intro: "도미노",
    tools: "Cinema 4D, After Effects",
    duration: "3주",
    program: "Cinema 4D 포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/04a81ef843210002432143210fedcba9.jpg",
    video: "https://www.youtube.com/embed/4lgEquMzlWw",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21012&selMater=%EB%AA%A8%EC%85%98%EA%B7%B8%EB%9E%98%ED%94%BD",
  },
  {
    id: "21137",
    course: "cg",
    title: "전효찬 학생 작품",
    student: "전효찬",
    branch: "울산지점",
    date: "2026-07-24",
    category: "CG/마야",
    intro: "3D modeling portfolio",
    tools: "Maya, Substance 3D Painter",
    duration: "3달",
    program: "마야포폴",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/034ef4c843210002432143210fedcba9.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21137&selMater=vfx",
  },
  {
    id: "21066",
    course: "cg",
    title: "김용준 학생 작품",
    student: "김용준",
    branch: "광주지점",
    date: "2026-05-18",
    category: "CG/마야",
    intro: "rabbit",
    tools: "마야, 섭스페인터, 에펙, 포토샵, 프리미어",
    duration: "1개월",
    program: "maya 포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/0376aa1c0fed00020fed0fedcba98765.jpg",
    video: "https://www.youtube.com/embed/-1QSJu-cRKU",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21066&selMater=vfx",
  },
  {
    id: "21060",
    course: "cg",
    title: "박주하 학생 작품",
    student: "박주하",
    branch: "인천지점",
    date: "2026-05-18",
    category: "CG/마야",
    intro: "AI 사이버 액션",
    tools: "AI, 블렌더, 서브스턴스 페인터, 에펙",
    duration: "1주",
    program: "블렌더 VFX 정규과정",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/031c4f1c0fed00020fed0fedcba98765.jpg",
    video: "https://www.youtube.com/embed/iDFXK0lX5YU",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21060&selMater=vfx",
  },
  {
    id: "21011",
    course: "cg",
    title: "오수빈 학생 작품",
    student: "오수빈",
    branch: "대전지점",
    date: "2026-05-08",
    category: "CG/마야",
    intro: "LNER A1",
    tools: "Maya, V-Ray, Mudbox, ZBrush, Substance Painter, After Effects, Photoshop",
    duration: "4개월",
    program: "마야 포폴",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/03a4e8a0cba90002cba9cba987654321.jpg",
    video: "https://www.youtube.com/embed/DY8LKcpmPwE",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21011&selMater=vfx",
  },
  {
    id: "20915",
    course: "cg",
    title: "손준일 학생 작품",
    student: "손준일",
    branch: "수원지점",
    date: "2026-03-17",
    category: "CG/마야",
    intro: "마야 모델링 포트폴리오",
    tools: "Maya, ZBrush, Substance Painter, Photoshop, After Effects, Nuke",
    duration: "8개월",
    program: "마야 CG 과정",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/03b7aa84876500028765876543210fed.jpg",
    video: "https://www.youtube.com/embed/xljxYqGSNic",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=20915&selMater=vfx",
  },
  {
    id: "20770",
    course: "cg",
    title: "유영훈 학생 작품",
    student: "유영훈",
    branch: "강남지점",
    date: "2026-01-08",
    category: "CG/마야",
    intro: "Caught at Dawn",
    tools: "마야, 블렌더, 에프터이펙트, 프리미어",
    duration: "5개월",
    program: "애니메이션 과정",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/유영훈 애니메이션.png",
    video: "https://www.youtube.com/embed/VyAIYBQROd8",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=20770&selMater=vfx",
  },
  {
    id: "21194",
    course: "interior",
    title: "황인성 학생 작품",
    student: "황인성",
    branch: "광주지점",
    date: "2026-09-16",
    category: "건축/인테리어",
    intro: "Interior",
    tools: "3Ds Max",
    duration: "16일",
    program: "인테리어 포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/031130c09876000598769876543210fe.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21194&selMater=interior",
  },
  {
    id: "21177",
    course: "interior",
    title: "김예진 학생 작품",
    student: "김예진",
    branch: "노원지점",
    date: "2026-08-25",
    category: "건축/인테리어",
    intro: "INTERIOR SCENE",
    tools: "스케치업, 엔스케이프, 에프터이펙트",
    duration: "5일",
    program: "Enscape",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/03d0df90cba90002cba9cba987654321.png",
    video: "https://www.youtube.com/embed/t8Frx0-AEYU",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21177&selMater=interior",
  },
  {
    id: "21143",
    course: "interior",
    title: "김준일 학생 작품",
    student: "김준일",
    branch: "청주지점",
    date: "2026-07-29",
    category: "건축/인테리어",
    intro: "비즈니스 허브 공간 디자인",
    tools: "AutoCAD, SketchUp, Photoshop",
    duration: "4주",
    program: "인테리어포폴",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/032a7c04876500028765876543210fed.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21143&selMater=interior",
  },
  {
    id: "21120",
    course: "interior",
    title: "허태훈 포트폴리오",
    student: "허태훈",
    branch: "인천지점",
    date: "2026-07-15",
    category: "건축/인테리어",
    intro: "The Horizon",
    tools: "SketchUp",
    duration: "15일",
    program: "인테리어포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/03ad8b8843210002432143210fedcba9.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21120&selMater=interior",
  },
  {
    id: "21100",
    course: "interior",
    title: "김은지 학생 작품",
    student: "김은지",
    branch: "광주지점",
    date: "2026-06-16",
    category: "건축/인테리어",
    intro: "Interior",
    tools: "3Ds Max, Photoshop, ChatGPT, Midjourney",
    duration: "16일",
    program: "인테리어 포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/0380d5ac0fed00020fed0fedcba98765.jpg",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21100&selMater=interior",
  },
  {
    id: "21036",
    course: "interior",
    title: "이수민 학생 작품",
    student: "이수민",
    branch: "노원지점",
    date: "2026-05-12",
    category: "건축/인테리어",
    intro: "ICE CUBE 복합문화공간",
    tools: "3ds Max, V-Ray, Photoshop",
    duration: "7주",
    program: "건축/인테리어 포트폴리오",
    img: "//cdn.koreaedugroup.com/sbsfile/gallery_img/03628c9843210002432143210fedcba9.png",
    sourceHref: "https://sbsart.com/portfolio/view.asp?seq=21036&selMater=interior",
  },
];

export const courseLabels: Record<CourseKey, { label: string; tools: string }> = {
  graphic: { label: "그래픽 디자인", tools: "Photoshop · Illustrator" },
  motion: { label: "모션그래픽", tools: "Premiere · After Effects · C4D" },
  cg: { label: "CG / 3D", tools: "ZBrush · Rigging · Animation · Maya" },
  interior: { label: "인테리어 디자인", tools: "CAD · SketchUp · 3ds Max · Enscape" },
};

export function getPortfolioItem(id: string) {
  return portfolioItems.find((item) => item.id === id);
}
